on: push
name: CI
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    container: nixos/nix
    steps:
    - uses: actions/checkout@master
    - name: Cache nix store
      uses: actions/cache@v1
      with:
        path: /nix/store
        key: ${{ runner.os }}-nix
    - run: nix-shell --pure --run "make all test"
      env:
        ENVIRONMENT: production
