on: push
name: CI
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    container: nixos/nix
    steps:
    - uses: actions/checkout@master
    - run: nix-shell --pure --run "make all test"
      env:
        ENVIRONMENT: production
