on: push
name: CI
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    container: node:10
    steps:
    - uses: actions/checkout@master
    - run: make all test
      env:
        ENVIRONMENT: production
